config/routes.rb
Rails.application.routes.draw do
  concern :change_status do
    patch 'activate', on: :member
    patch 'deactivate', on: :member
  end

  concern :auditable do |options|
    scope module: options[:parent] do
      resources :audits, only: [:index]
    end
  end

  resources :location_types do
    scope module: :location_types do
      resources :locations, only: [:index]
    end

    concerns :auditable, parent: :location_types
  end

  resources :locations do
    resources :prints, only: [:new, :create]

    concerns :change_status
    concerns :auditable, parent: :locations
    scope module: :locations do
      resources :children, only: [:index]
      resources :labwares, only: [:index]
    end

  end

  resources :labwares, only: [:show] do
    concerns :auditable, parent: :labwares
  end

  resources :scans, only: [:new, :create]

  resources :upload_labware, only: [:new, :create]
  resources :move_locations, only: [:new, :create]
  resources :empty_locations, only: [:new, :create]
  resources :location_finder, only: [:new, :create]
  resources :searches, only: [:new, :create, :show]

  resources :users do
    concerns :auditable, parent: :users
    concerns :change_status
  end

  resources :teams do
    concerns :auditable, parent: :teams
  end

  resources :printers do
    concerns :auditable, parent: :printers
  end

  root 'scans#new'

  namespace :api do
    get 'locations/info', to: 'locations#info'
    post 'labwares/searches', to: 'labwares/searches#create'
    post 'labwares/locations', to: 'labwares/locations#create'
 
    post 'labwares_by_barcode', to: 'labwares#by_barcode'

    put 'coordinates', to: 'coordinates#update'

    resources :locations, param: :barcode, except: [:destroy] do
      scope module: :locations do
        resources :labwares, only: [:index]
        resources :children, only: [:index]
        resources :descendants, only: [:index]
        resources :coordinates, only: [:index, :update]
      end

      concerns :auditable, parent: :locations
    end

    resources :location_types, except: [:destroy] do
      scope module: :location_types do
        resources :locations, only: [:index]
      end

      concerns :auditable, parent: :location_types
    end

    resources :scans, only: [:create]

    resources :labwares, only: [:create]

    resources :labwares, param: :barcode, only: [:show, :index] do
      concerns :auditable, parent: :labwares
    end

    resources :searches, only: [:create]
  end

  unless Rails.env.development?
    match '(errors)/:status', to: 'errors#show', constraints: { status: /\d{3}/ }, via: :all
  end

  match 'test_exception_notifier', controller: 'application', action: 'test_exception_notifier', via: :get

  match '/about', to: 'about#show', via: :get

end

app/controllers/upload_labware_controller.rb
# frozen_string_literal: true

# UploadLabwareController
class UploadLabwareController < ApplicationController
  def new
    @upload_labware = UploadLabwareForm.new
  end

  def create
    @upload_labware = UploadLabwareForm.new

    if @upload_labware.submit(params)
      redirect_to new_upload_labware_path, notice: I18n.t('success.messages.uploaded', resource: 'Labware')
    else
      render :new
    end
  end
end

app/views/upload_labware/_form.html.erb
<%= form_for @upload_labware, url: upload_labware_index_path do |f| %>
  <fieldset>
    <legend>Upload Labware</legend>
    <div class="form-description-box">
      Upload a csv file with the following columns:
      <ol>
        <li>1. Barcodes of the locations you wish to scan into</li>
        <li>2. Labware barcodes</li>
      </ol>
      The file should also have column headers, but it doesn't matter what they are.
    </div>
    <br/>
    <div>
      <ul>
        <li>
          <%= render "user_code", object: f %>
        </li>
        <li>
          <div><%= f.label :file, 'Upload a file here*' %></div>
          <div><%= f.file_field :file %></div>
        </li>
        <li>
          <%= f.submit "Go!", data: {disable_with: "uploading..."} %>
        </li>
      </ul>
    </div>
  </fieldset>
<% end %>

app/views/upload_labware/new.html.erb
<section class="<%= header.to_css_class %>">
  <%= render "error_messages", target: @upload_labware %>
  <%= render "form" %>
</section>