config/routes.rb
Rails.application.routes.draw do
  concern :change_status do
    patch 'activate', on: :member
    patch 'deactivate', on: :member
  end

  concern :auditable do |options|
    scope module: options[:parent] do
      resources :audits, only: [:index]
    end
  end

  resources :location_types do
    scope module: :location_types do
      resources :locations, only: [:index]
    end

    concerns :auditable, parent: :location_types
  end

  resources :locations do
    resources :prints, only: [:new, :create]

    concerns :change_status
    concerns :auditable, parent: :locations
    scope module: :locations do
      resources :children, only: [:index]
      resources :labwares, only: [:index]
    end

  end

  resources :labwares, only: [:show] do
    concerns :auditable, parent: :labwares
  end

  resources :scans, only: [:new, :create]

  resources :upload_labware, only: [:new, :create]
  resources :move_locations, only: [:new, :create]
  resources :empty_locations, only: [:new, :create]
  resources :location_finder, only: [:new, :create]
  resources :searches, only: [:new, :create, :show]

  resources :users do
    concerns :auditable, parent: :users
    concerns :change_status
  end

  resources :teams do
    concerns :auditable, parent: :teams
  end

  resources :printers do
    concerns :auditable, parent: :printers
  end

  root 'scans#new'

  namespace :api do
    get 'locations/info', to: 'locations#info'
    post 'labwares/searches', to: 'labwares/searches#create'
    post 'labwares/locations', to: 'labwares/locations#create'
 
    post 'labwares_by_barcode', to: 'labwares#by_barcode'

    put 'coordinates', to: 'coordinates#update'

    resources :locations, param: :barcode, except: [:destroy] do
      scope module: :locations do
        resources :labwares, only: [:index]
        resources :children, only: [:index]
        resources :descendants, only: [:index]
        resources :coordinates, only: [:index, :update]
      end

      concerns :auditable, parent: :locations
    end

    resources :location_types, except: [:destroy] do
      scope module: :location_types do
        resources :locations, only: [:index]
      end

      concerns :auditable, parent: :location_types
    end

    resources :scans, only: [:create]

    resources :labwares, only: [:create]

    resources :labwares, param: :barcode, only: [:show, :index] do
      concerns :auditable, parent: :labwares
    end

    resources :searches, only: [:create]
  end

  unless Rails.env.development?
    match '(errors)/:status', to: 'errors#show', constraints: { status: /\d{3}/ }, via: :all
  end

  match 'test_exception_notifier', controller: 'application', action: 'test_exception_notifier', via: :get

  match '/about', to: 'about#show', via: :get

end

app/controllers/prints_controller.rb
# frozen_string_literal: true

# PrintsController
class PrintsController < ApplicationController
  layout false

  def new
    @location = current_resource
  end

  def create
    label_template_name = Rails.configuration.label_templates[params[:barcode_type]]
    @print_barcode = LabelPrinter.new(printer: params[:printer_id],
                                      locations: location_ids,
                                      label_template_name: label_template_name,
                                      copies: params[:copies].to_i)
    @print_barcode.post

    respond_to do |format|
      @message = @print_barcode.message + message_suffix
      @message_type = if @print_barcode.response_ok?
                        'notice'
                      else
                        'alert'
                      end
      format.js { render 'prints/create' }
    end
  end

  private

  def current_resource
    @current_resource ||= Location.find(params[:location_id]) if params[:location_id]
  end

  def location_ids
    params[:print_child_barcodes] ? location_resource.child_ids : params[:location_id]
  end

  def location_resource
    Location.find(params[:location_id])
  end

  def message_suffix
    suffix = params[:print_child_barcodes] ? ' for each child of' : ' for'
    suffix + " location: #{current_resource.name}"
  end
end

app/views/prints/_form.html.erb
<%= render "error_messages", target: @location %>
<%= form_tag(location_prints_path(@location), remote: true) do %>
  <fieldset>
    <ul>
      <li>
        <%= label_tag :printer_id %>
        <%= select_tag :printer_id, options_from_collection_for_select(Printer.all, :id, :name) %>
      </li>
      <li>
        <%= label_tag :copies, "Copies" %>
        <%= number_field_tag 'copies', '1', min: 1 %>
      </li>
      <li>
        <%= radio_button_tag 'barcode_type', '1D', true %>
        <%= label_tag :barcode_type_1D, "1D" %>
      </li>
      <li>
        <%= radio_button_tag 'barcode_type', '2D' %>
        <%= label_tag :barcode_type_2D, "2D" %>
      </li>
      <% if @location.has_child_locations? %>
        <li>
          <%= check_box_tag :print_child_barcodes %>
          <%= label_tag :print_child_barcodes, 'Print Child Barcodes?' %>
        </li>
      <% end %>
    </ul>
    <%= submit_tag "Print" %>
  </fieldset>
<% end %>

app/views/prints/create.js.erb
// display the response message to the user (ajax does not have access to the session to set flash normally)
$(".flash").show()
<% if @message_type == 'notice' %>
   <%= render partial: "application/flash_notice", object: @message %>
<% else %>
   <%= render partial: 'application/flash_alert', object: @message %>
<% end %>

// close the dialog window
jQuery('.ui-icon-closethick').trigger('click');

app/views/prints/new.html.erb
<%= render "form" %>

app/views/prints/new.js.erb
$("#print-form").addDialog("<%= escape_javascript(render('form')) %>", "Reprint Barcode");