config/routes.rb
Rails.application.routes.draw do
  concern :change_status do
    patch 'activate', on: :member
    patch 'deactivate', on: :member
  end

  concern :auditable do |options|
    scope module: options[:parent] do
      resources :audits, only: [:index]
    end
  end

  resources :location_types do
    scope module: :location_types do
      resources :locations, only: [:index]
    end

    concerns :auditable, parent: :location_types
  end

  resources :locations do
    resources :prints, only: [:new, :create]

    concerns :change_status
    concerns :auditable, parent: :locations
    scope module: :locations do
      resources :children, only: [:index]
      resources :labwares, only: [:index]
    end

  end

  resources :labwares, only: [:show] do
    concerns :auditable, parent: :labwares
  end

  resources :scans, only: [:new, :create]

  resources :upload_labware, only: [:new, :create]
  resources :move_locations, only: [:new, :create]
  resources :empty_locations, only: [:new, :create]
  resources :location_finder, only: [:new, :create]
  resources :searches, only: [:new, :create, :show]

  resources :users do
    concerns :auditable, parent: :users
    concerns :change_status
  end

  resources :teams do
    concerns :auditable, parent: :teams
  end

  resources :printers do
    concerns :auditable, parent: :printers
  end

  root 'scans#new'

  namespace :api do
    get 'locations/info', to: 'locations#info'
    post 'labwares/searches', to: 'labwares/searches#create'
    post 'labwares/locations', to: 'labwares/locations#create'
 
    post 'labwares_by_barcode', to: 'labwares#by_barcode'

    put 'coordinates', to: 'coordinates#update'

    resources :locations, param: :barcode, except: [:destroy] do
      scope module: :locations do
        resources :labwares, only: [:index]
        resources :children, only: [:index]
        resources :descendants, only: [:index]
        resources :coordinates, only: [:index, :update]
      end

      concerns :auditable, parent: :locations
    end

    resources :location_types, except: [:destroy] do
      scope module: :location_types do
        resources :locations, only: [:index]
      end

      concerns :auditable, parent: :location_types
    end

    resources :scans, only: [:create]

    resources :labwares, only: [:create]

    resources :labwares, param: :barcode, only: [:show, :index] do
      concerns :auditable, parent: :labwares
    end

    resources :searches, only: [:create]
  end

  unless Rails.env.development?
    match '(errors)/:status', to: 'errors#show', constraints: { status: /\d{3}/ }, via: :all
  end

  match 'test_exception_notifier', controller: 'application', action: 'test_exception_notifier', via: :get

  match '/about', to: 'about#show', via: :get

end

app/controllers/api/location_types/audits_controller.rb
# frozen_string_literal: true

# Api::LocationTypes::AuditsController
class Api::LocationTypes::AuditsController < ApiController
  def index
    render json: current_resource
  end

  private

  def current_resource
    LocationType.find(params[:location_type_id]).audits if params[:location_type_id]
  end
end

app/controllers/api/location_types/locations_controller.rb
# frozen_string_literal: true

# Api::LocationTypes::LocationsController
class Api::LocationTypes::LocationsController < ApiController
  def index
    render json: current_resource
  end

  private

  def current_resource
    LocationType.find(params[:location_type_id]).locations if params[:location_type_id]
  end
end

app/controllers/api/location_types_controller.rb
# frozen_string_literal: true

# Api::LocationTypesController
class Api::LocationTypesController < ApiController
  def index
    render json: LocationType.all
  end

  def show
    render json: current_resource
  end

  def create
    @location_type = LocationTypeForm.new
    process_location_type
  end

  def update
    @location_type = LocationTypeForm.new(current_resource)
    process_location_type
  end

  private

  def current_resource
    LocationType.find(params[:id]) if params[:id]
  end

  def process_location_type
    if @location_type.submit(params)
      render json: @location_type, serializer: LocationTypeSerializer
    else
      render json: { errors: @location_type.errors.full_messages }, status: :unprocessable_entity
    end
  end
end

app/controllers/location_types/audits_controller.rb
# frozen_string_literal: true

# LocationTypes::AuditsController
class LocationTypes::AuditsController < ApplicationController
  include Auditing
end

app/controllers/location_types/locations_controller.rb
# frozen_string_literal: true

# LocationTypes::LocationsController
class LocationTypes::LocationsController < ApplicationController
  before_action :locations, only: [:index]

  def index; end

  protected

  def locations
    LocationType.find(params[:location_type_id]).locations if params[:location_type_id]
  end

  helper_method :locations
end

app/controllers/location_types_controller.rb
# frozen_string_literal: true

# LocationTypesController
class LocationTypesController < ApplicationController
  before_action :location_types, only: [:index]
  before_action :set_location_type, except: [:index]

  def index; end

  def show; end
  def new; end

  def edit; end

  def create
    if @location_type.submit(params)
      redirect_to location_types_path, notice: I18n.t('success.messages.created', resource: 'Location type')
    else
      render :new
    end
  end

  def update
    if @location_type.submit(params)
      redirect_to location_types_path, notice: I18n.t('success.messages.updated', resource: 'Location type')
    else
      render :edit
    end
  end

  def delete
    respond_to do |format|
      format.js
    end
  end

  def destroy
    respond_to do |format|
      if @location_type.destroy(params)
        flash_keep 'Location type successfully deleted'
        format.js { render js: "window.location.pathname='#{location_types_path}'" }
      else
        format.js
      end
    end
  end

  protected

  def location_types
    @location_type ||= LocationType.ordered
  end

  def set_location_type
    @location_type = LocationTypeForm.new(current_resource)
  end

  helper_method :location_types

  private

  def current_resource
    @current_resource ||= LocationType.find(params[:id]) if params[:id]
  end
end

app/views/location_types/_form.html.erb
<%= form_for @location_type do |f| %>
  <fieldset>
    <legend><%= header.to_s %></legend>
    <ul>
      <li>
        <%= render "user_code", object: f %>
      </li>
      <li>
        <%= f.label :name, 'Name*' %>
        <%= f.text_field :name %>
      </li>
    </ul>
    <%= f.submit %>
  </fieldset>
<% end %>

app/views/location_types/_location_type.html.erb
<article id="<%= dom_id(location_type) %>" class="drilldown" data-behavior="list" data-type="location_type" data-id="<%= location_type.id %>">
    <div>
      <%= drilldown_link %>
    </div>
    <div class="id">
      <%= location_type.id %>.
    </div>
    <div class="name">
      <%= location_type.name %>
    </div>
    <div>
      <%= link_to image_tag("edit.png", alt: "Edit", title: "Edit"), edit_location_type_path(location_type) %> 
    </div>
    <div>
      <% location_type.destroyable do %>
        <%= link_to image_tag("delete.png", alt: "Delete", title: "Delete"), [:delete, location_type], remote: true %>
      <% end %>
    </div>
    <div>
      <%= audits_link %>
    </div>
</article>

app/views/location_types/delete.js.erb
$("#delete-form").addDialog("<%= escape_javascript(render('delete')) %>", "Delete Location Type");

app/views/location_types/destroy.js.erb
$("#errors").remove();
$("#delete-form").prepend("<%= escape_javascript(render('error_messages', target: @location_type)) %>");

app/views/location_types/edit.html.erb
<section class="edit-location-type">
  <%= render "error_messages", target: @location_type %>
  <%= render "form" %> 
</section>

app/views/location_types/index.html.erb
<section class="<%= header.to_css_class %> list">
    <h1>
      <%= header.to_s %>
    </h1>
    <div>
      <%= link_to "Add new location type", new_location_type_path %>
    </div>
    <div class="collection" data-behavior="location_types-list">
      <%= render location_types %>
    </div>
    <div id="delete-form"></div>
</section>

app/views/location_types/new.html.erb
<section class="<%= header.to_css_class %>">
  <%= render "error_messages", target: @location_type %>
  <%= render "form" %> 
</section>

app/views/location_types/show.html.erb
<%= render @location_type %>